"""
generate_pinned_requirements.py — Standalone Hash-Pinned Requirements Generator
Data Poisoning Protection Course — Lab 7.2

PURPOSE
-------
Reads a requirements.txt in the current directory and writes a
requirements_pinned.txt in pip's hash-checking format.

Each entry becomes:
    package==version \\
        --hash=sha256:<hash>

The hashes in this script are DETERMINISTIC DEMO VALUES generated from
sha256(package_name + version). They are NOT real wheel hashes.

To use in production:
  1. Run this script to generate the file structure.
  2. For each package, download the real wheel:
       pip download --no-deps -d ./wheels <package>==<version>
  3. Get the real hash:
       pip hash ./wheels/<wheel>.whl
  4. Replace the DEMO hash in requirements_pinned.txt with the real one.

USAGE
-----
    python generate_pinned_requirements.py
    python generate_pinned_requirements.py --input reqs.txt --output reqs_pinned.txt

EXIT CODES
----------
    0  — success
    1  — input file not found or parse error
"""

import argparse
import hashlib
import hmac
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Hash generation (deterministic demo)
# ---------------------------------------------------------------------------

# This key is public and intentional — it only produces demo hashes.
# It is NOT a secret. Replace all output hashes with real pip hash output.
_DEMO_HMAC_KEY = b"udege-lab-7.2-demo-not-a-real-hash"


def demo_sha256_for_package(package_name: str, version: str) -> str:
    """
    Generate a deterministic fake SHA-256 hash for (package, version).

    The hash is:
        HMAC-SHA256(key=_DEMO_HMAC_KEY, msg="{lowercase_name}=={version}")

    This produces a consistent 64-character hex string that is the same every
    time this script runs with the same inputs — useful for diffing outputs and
    for students to understand the format without needing live pip downloads.

    NEVER use this hash in production. Obtain real hashes from pip hash.
    """
    payload = f"{package_name.lower()}=={version}".encode("utf-8")
    return hmac.new(_DEMO_HMAC_KEY, payload, digestmod=hashlib.sha256).hexdigest()


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def parse_requirements_line(line: str):
    """
    Parse a single requirements.txt line.

    Returns (pkg_name, version_str) or None if the line should be skipped
    (blank, comment, or unparseable).

    Handles common specifiers:
        torch>=2.0.0         -> ("torch", "2.0.0")
        torch==2.0.0         -> ("torch", "2.0.0")
        torch~=2.0.0         -> ("torch", "2.0.0")
        torch                -> ("torch", "0.0.0")   # no version specified
        torch[cuda]>=2.0.0   -> ("torch[cuda]", "2.0.0")
        -r other.txt         -> None  (recursive includes not supported)
        # comment            -> None
    """
    line = line.strip()

    if not line or line.startswith("#"):
        return None

    # Skip pip options and recursive includes
    if line.startswith("-"):
        return None

    # Match: name[extras]  operator  version
    pattern = re.compile(
        r"^([A-Za-z0-9_\-\.\[\]]+)"   # package name (with optional extras)
        r"\s*[><=!~^]+\s*"              # version operator (required for version)
        r"([0-9][0-9a-zA-Z.\-*]*)?"    # version string
    )
    match = pattern.match(line)

    if match:
        pkg_name    = match.group(1).strip()
        version_str = match.group(2) or "0.0.0"
        return pkg_name, version_str

    # Package with no version specifier
    bare = re.match(r"^([A-Za-z0-9_\-\.\[\]]+)$", line)
    if bare:
        return bare.group(1), "0.0.0"

    return None


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

def generate_pinned_requirements(input_path: str, output_path: str) -> int:
    """
    Read *input_path*, generate hash-pinned output to *output_path*.

    Returns 0 on success, 1 on error.
    """
    input_file  = Path(input_path)
    output_file = Path(output_path)

    if not input_file.exists():
        print(f"[ERROR] Input file not found: {input_path}")
        return 1

    raw_lines = input_file.read_text(encoding="utf-8").splitlines()
    print(f"[*] Reading: {input_path} ({len(raw_lines)} lines)")

    output_lines = [
        "# ============================================================",
        "# Hash-pinned requirements",
        "# Generated by generate_pinned_requirements.py",
        "#",
        "# IMPORTANT: The sha256 hashes below are DEMO VALUES.",
        "# They are sha256(package_name+version) — NOT real wheel hashes.",
        "# Replace each hash with the real one from:",
        "#   pip download --no-deps -d ./wheels <pkg>==<ver>",
        "#   pip hash ./wheels/<wheel>.whl",
        "#",
        "# Install with:",
        "#   pip install --require-hashes -r requirements_pinned.txt",
        "# ============================================================",
        "",
    ]

    processed = []
    skipped   = []

    for raw_line in raw_lines:
        line = raw_line.strip()

        # Pass through blank lines and comments
        if not line or line.startswith("#"):
            output_lines.append(raw_line)
            continue

        parsed = parse_requirements_line(line)

        if parsed is None:
            output_lines.append(f"# SKIPPED (unsupported format): {raw_line}")
            skipped.append(raw_line)
            continue

        pkg_name, version = parsed
        demo_hash = demo_sha256_for_package(pkg_name, version)

        # Write in pip hash-check format
        # The backslash continuation is required by pip for multi-line entries
        pinned_entry = (
            f"{pkg_name}=={version} \\\n"
            f"    --hash=sha256:{demo_hash}  # DEMO HASH — replace with real pip hash"
        )
        output_lines.append(pinned_entry)
        output_lines.append("")  # blank line between entries for readability

        processed.append((pkg_name, version, demo_hash))

    # Write the output file
    output_content = "\n".join(output_lines) + "\n"
    output_file.write_text(output_content, encoding="utf-8")

    # --- Print summary ---
    print(f"\n[+] Written to: {output_path}")
    print(f"    Pinned packages: {len(processed)}")
    print(f"    Skipped lines  : {len(skipped)}")
    print()

    if processed:
        print(f"  {'Package':<30} {'Version':<15} {'Demo Hash (first 20 chars)'}")
        print(f"  {'-'*30} {'-'*15} {'-'*26}")
        for pkg, ver, h in processed:
            print(f"  {pkg:<30} {ver:<15} {h[:20]}...")
        print()

    if skipped:
        print("  Skipped lines (unsupported format):")
        for s in skipped:
            print(f"    {s}")
        print()

    print("[REMINDER] Replace DEMO hashes with real hashes before production use.")
    print("           See the comment block at the top of the generated file.")

    return 0


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a hash-pinned requirements.txt from an existing requirements file. "
            "The generated hashes are DEMO VALUES — replace them with real pip hash output."
        )
    )
    parser.add_argument(
        "--input",
        "-i",
        default="requirements.txt",
        help="Input requirements file (default: requirements.txt)",
    )
    parser.add_argument(
        "--output",
        "-o",
        default="requirements_pinned.txt",
        help="Output hash-pinned requirements file (default: requirements_pinned.txt)",
    )

    args   = parser.parse_args()
    retval = generate_pinned_requirements(args.input, args.output)
    sys.exit(retval)


if __name__ == "__main__":
    main()


# ---------------------------------------------------------------------------
# Production workflow reference (comments only)
# ---------------------------------------------------------------------------
#
# Step 1 — Pin versions in requirements.txt:
#   pip freeze > requirements.txt
#   # or manually: echo "torch==2.1.0" >> requirements.txt
#
# Step 2 — Download wheels (no install) and get real hashes:
#   mkdir -p wheels
#   pip download --no-deps -d wheels -r requirements.txt
#   for whl in wheels/*.whl; do
#       echo "$(pip hash $whl)"
#   done
#
# Step 3 — Build requirements_pinned.txt with real hashes:
#   # Run this script, then replace DEMO hashes with real ones from Step 2.
#   python generate_pinned_requirements.py
#
# Step 4 — Verify installation with hash checking:
#   pip install --require-hashes -r requirements_pinned.txt
#   # pip will reject any wheel whose hash does not match.
#
# Step 5 — Automate in CI/CD:
#   - Store requirements_pinned.txt in version control.
#   - CI step: pip install --require-hashes -r requirements_pinned.txt
#   - Update hashes when upgrading packages (re-run Steps 2-3).
#
# Tools that automate hash management:
#   - pip-compile --generate-hashes (from pip-tools)
#   - pipenv lock
#   - poetry (with lock file)
